board/urls.py
# -*- coding:utf-8 -*-
# --author:'xiawei'
# --date: '2017/12/20'
from rest_framework.routers import DefaultRouter

from . import views
# Backbone创建的url不需要最后的斜杠，而Django需要。通过以下语句来添加结尾斜杠
router = DefaultRouter(trailing_slash=False)
# router = DefaultRouter()
router.register(r'sprints', views.SprintViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

scrum/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from django.conf.urls import include, url

from board.urls import router

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
    url(r'^$', TemplateView.as_view(template_name='board/index.html'))
]

board/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.


class Sprint(models.Model):
    """development iteration period."""
    name = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(blank=True, default='')
    end = models.DateField(unique=True)

    def __str__(self):
        return self.name or _('Sprint ending %s') % self.end


class Task(models.Model):
    """Unit of work to be done"""
    STATUS_TODO = 1
    STATUS_IN_PROGRESS = 2
    STATUS_TESTING = 3
    STATUS_DONE = 4

    STATUS_CHOICE = (
        (STATUS_TODO, _('Not Started')),
        (STATUS_IN_PROGRESS, _('In progress')),
        (STATUS_TESTING, _('Testing')),
        (STATUS_DONE, _('Done')),
    )
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    sprint = models.ForeignKey(Sprint, blank=True, null=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=STATUS_TODO)
    order = models.SmallIntegerField(default=0)
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    started = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)
    completed = models.DateField(blank=True, null=True)


def __str__(self):
    return self.name

board/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import viewsets, authentication, permissions, filters

from board.models import Sprint, Task
from board.serializers import SprintSerializer, TaskSerializer, UserSerializer
from django.contrib.auth import get_user_model

User = get_user_model()


class DefaultMixin(object):
    """default setting for view authentication, permission, filtering and pagination"""
    authentication_class = (
        authentication.BasicAuthentication,
        authentication.TokenAuthentication,
    )
    permission_classes = (
        permissions.IsAuthenticated,
    )
    paginate_by = 25
    paginate_by_param = 'page_size'
    max_paginate_by = 100

    # 添加过滤器 下面保存了一个所有可用的filter_backends列表，通过已有的ViewSet启用这些过滤器。
    # 对应views.py中的代码
    filter_backends = (
        # filters.BaseFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )


class SprintViewSet(DefaultMixin, viewsets.ModelViewSet):
    """API endpoint for listing and creating sprint"""
    queryset = Sprint.objects.order_by('end')
    serializer_class = SprintSerializer

    # 使用过滤器
    search_fields = ('name',)
    ordering_fields = ('end', 'name',)


class TaskViewSet(DefaultMixin, viewsets.ModelViewSet):
    """API endpoint for listing and creating task."""
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    # 使用过滤器
    search_fields = ('name', 'description')
    ordering_fields = ('name', 'order', 'started', 'due', 'completed')


class UserViewSet(DefaultMixin, viewsets.ReadOnlyModelViewSet):
    """API endpoint for listing users"""
    lookup_field = User.USERNAME_FIELD
    lookup_url_kwarg = User.USERNAME_FIELD

    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = UserSerializer

    # 使用过滤器
    search_fields = (User.USERNAME_FIELD,)

board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <title>Scrum board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'board/css/board.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/normalize.css' %}">
    {# 定义home-template #}
    <script type="text/html" id="home-template">
    {# <h1>Welcome to my Scrum Board Project!</h1> #}
        <h2>Your Sprints</h2>
        <button class="add" type="submit">Add Sprint</button>
        <% if (sprints !== null) { %>
            <div class="sprints">
                <% _.each(sprints.models, function(sprint) { %>
                    <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
                        <%- sprint.get('name') %> <br>
                        <span>DUE BY <%- sprint.get('end') %></span>
                    </a>
                <% }); %>
            </div>
        <% } else { %>
            <h3 class="loading">Loading...</h3>
        <% } %>
    </script>

    <script id="login-template" type="text/html">
        <form action="" method="post">
            <label for="id_username">Username</label>
            <input id="id_username" type="text" name="username" maxlength="30" required/>
            <label for="id_password">Password</label>
            <input id="id_password" type="password" name="password" required/>
            <button type="submit">Login</button>
        </form>
    </script>
    <script id="header-template" type="text/html">
        <span class="title">
            Scrum board Example
        </span>
        <% if(authenticated){ %>
            <nav>
                <a href="/" class="button">Your Sprints</a>
                <a href="#" class="logout button">Logout</a>
            </nav>
        <% } %>
    </script>
    <script type="text/html" id="new-sprint-template">
        <form action="" method="post">
            <label for="id_name">Sprint name</label>
            <input id="id_name" type="text" name="name" maxlength="100" required />
            <label for="id_end">End Date</label>
            <input id="id_end" type="date" name="end"/>
            <label for="id_description">Description</label>
            <textarea name="description" id="id_description" cols="50" rows="10"></textarea>
            <button class="cancel">Cancel</button>
            <button type="submit">Create</button>
        </form>
    </script>
    <script type="text/html" id="sprint-template">
        <% if (sprint !== null) { %>
            <% if (!sprint.invalid) { %>
                <h2><%- sprint.get('name') %></h2>
                <span class="due-date">Due <%- sprint.get('end') %></span>
                <p class="description"><%- sprint.get('description') %></p>
                <div class="tasks"></div>
            <% } else { %>
                <h1>Sprint <%- sprint.get('id') %> not found.</h1>
            <% } %>
        <% } else { %>
            <h1 class="loading">Loading....</h1>
        <% } %>
    </script>
    <script type="text/html" id="status-template">
        <h4><%- title %></h4>
        <div class="list"></div>
        <% if (sprint === null) { %>
            <button class="add" type="submit">Add Task</button>
        <% } %>
    </script>
    <script type="text/html" id="new-task-template">
        <form action="" method="post" class="add-task">
            <label for="id_name">Task Name</label>
            <input type="text" id="id_name" name="name" maxlength="100" required />
            <label for="id_description">Description</label>
            <textarea name="description" id="id_description" cols="30" rows="10"></textarea>
            <button class="create" type="submit">Create</button>
            <button class="cancel" type="submit">Cancel</button>
        </form>
    </script>
    <script type="text/html" id="task-item-template">
        <%- task.get('name') %>
    </script>
    <script type="text/html" id="task-detail-template">
        <div data-field="name" class="name" contenteditable="true">
            <%- task.get('name')%>
        </div>
        <div data-field="description" class="description" contenteditable="true">
            <%- task.get('description')%>
        </div>
        <div class="with-label">
            <div class="label">Due:</div>
            <div data-field="due" class="due date" contenteditable="true">
                <%- task.get('due')||empty %>
            </div>
        </div>
        <div class="with-label">
            <div class="label">Assigned To:</div>
            <div data-field="assigned" class="assigned" contenteditable="true">
                <%- task.get('assigned')||empty %>
            </div>
        </div>
        <form action="">
            <button class="cancel" type="submit">Close</button>
            <button class="save" hidden type="submit">Save</button>
        </form>
    </script>
</head>
<body>
    <!--该id对应router.js中的选择器-->
    <div id="content"></div>
    <!--注意引用顺序-->
    <script src="{% static 'board/vendor/jquery.js' %}"></script>
    <script src="{% static 'board/vendor/underscore.js' %}"></script>
    <script src="{% static 'board/vendor/backbone.js' %}"></script>

    <script id="config" type="text/json">
        {
            "models": {},
            "collections": {},
            "views": {},
            "router": null,

            "apiRoot": "{% url 'api-root' %}",
            "apiLogin": "{% url 'api-token' %}"
        }
    </script>

    <script src="{% static 'board/js/app.js' %}"></script>
    <script src="{% static 'board/js/models.js' %}"></script>
    <script src="{% static 'board/js/router.js' %}"></script>
    <script src="{% static 'board/js/views.js' %}"></script>
</body>
</html>